CREATE OR REPLACE FUNCTION fncCriarPlantacao(id_parcela PLANTACAO.ID_PARCELA_FK%TYPE,
                                                id_cultura PLANTACAO.ID_CULTURA_FK%TYPE) RETURN PLANTACAO.ID_PLANTACAO_PK%TYPE AS
id_plantacao PLANTACAO.ID_PLANTACAO_PK%TYPE := -1;
BEGIN
SAVEPOINT BEFORE_INSERT;
INSERT INTO PLANTACAO(ID_PLANTACAO_PK, ID_PARCELA_FK, ID_CULTURA_FK, DATA_COLHEITA, QUANTIDADE_COLHIDA) VALUES (DEFAULT,id_parcela,id_cultura,NULL,NULL) RETURNING ID_PLANTACAO_PK INTO id_plantacao;
DBMS_OUTPUT.PUT_LINE('Plantação criada. ID:');
RETURN id_plantacao;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK TO SAVEPOINT BEFORE_INSERT;
        DBMS_OUTPUT.PUT_LINE('Não foi possível criar a plantação.');
RETURN id_plantacao;
END;